config/routes.rb
Sunray::Application.routes.draw do


  devise_for :admins,
    :controllers => {
      :sessions => "admins/sessions",
      :registrations => 'admins/registrations',
      :confirmations => 'admins/confirmations',
      :passwords => "admins/passwords",
      :unlocks => "admins/unlocks",
      :accounts => "admins/accounts"
  }


  devise_for :users, :controllers => { 
    registrations: 'devise/registrations', 
    :sessions => "devise/sessions", 
    :passwords => 'devise/passwords', 
    :confirmations => 'devise/confirmations' 
  }

  authenticate :admin do
    namespace :admins do
      #mount Resque::Server.new, at: '/resque'
      resources :dashboards
      resources :accounts
    end  
  match "/admins" => 'admins/dashboards#index', as: :admins_root
  end
  
  resources :documentparents do as_routes end
  resources :documents do as_routes end
  resources :documentparts do as_routes end  
  root to: 'pages#index'
end

app/models/document.rb
class Document < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :documentparent
  has_many   :documentparts, :order => "position"
  
  validates :state, :presence => :true
  validates :documentparent_id, :uniqueness => {:scope => :state}
  
  def to_label
    "#{document_legal_name}"
  end
  
    
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

    

    active_scaffold :document do |config|
    # config.theme = :gray 
       
      config.list.page_links_inner_window = true
      config.list.sorting = { :state => :asc }
      
      columns[:state].label = "State"

      columns[:state].form_ui = :select 
      columns[:state].options[:options] = US_STATES 
       
      columns[:document_legal_name].label = "Document Legal Name"
      columns[:document_legal_name].inplace_edit = true 
      config.columns[:document_legal_name].options[:size] = 20
      
      columns[:document_type].label = "Type Of Document"
      columns[:document_type].inplace_edit = true
      columns[:document_type].form_ui = :select 
      columns[:document_type].options[:options] = [" ", "Hard Letter", "Soft Letter"]
      
      config.columns[:default_amount].options[:format] = :currency
      
      config.columns = [:state, :documentparent, :document_legal_name, :document_type]
      columns[:documentparent].label = "Document Name"
      columns[:documentparent].inplace_edit = true  
      columns[:documentparent].form_ui = :select 
      
      columns[:usps_barcode].label = "USPS BarCode?"
      columns[:documentparts].label = "Document Sections"
      columns[:signer].label = "Signer?" 
      columns[:add_todays_date].label = "Add Today's Date?"      
      
      columns[:use_default_amount].label = "Use Default Amount?"      
      columns[:soft_letter].label = "Soft Letter?"      
      columns[:sunray_logo].label = "Use Sunray Logo?"      
      columns[:add_completed_date].label = "Add Completed Date?"      
      columns[:to_from_address].label = "To and From Addresses?"      
      columns[:delivery_date_on_notice].label = "Delivery Date On Notice?" 
      columns[:total_amount_of_job].label = "Total Amount Of Job?"    
      columns[:balance_remaining].label = "Balance Ramaining?"             
      columns[:ariela_signature].label = "Ariela Signature?"  
      
      config.nested.add_link(:documentparts).label = "Document Parts"
     
      config.create.label = "Create New Document"  
      config.create.columns = :state,           
                           :documentparent,        
                           :document_legal_name, 
                           :document_type,
                           :default_amount                                                    
      config.create.columns.add_subgroup "Options" do |options_group|
         options_group.add :signer,
                           :delivery_date_on_notice,
                           :total_amount_of_job,
                           :balance_remaining,
                           :use_default_amount,
                           :soft_letter,
                           :sunray_logo,
                           :to_from_address,
                           :usps_barcode,
                           :ariela_signature,
                           :add_completed_date,
                           :add_todays_date
       end              
                          
      config.update.label = "Update Document"  
      config.update.columns = :state, 
                           :documentparent, 
                           :document_legal_name,                          
                           :document_type,
                           :default_amount                           
      config.update.columns.add_subgroup "Options" do |options_group|
        options_group.collapsed = true
        options_group.add :signer,
                           :delivery_date_on_notice,
                           :total_amount_of_job,
                           :balance_remaining,
                           :use_default_amount,
                           :soft_letter,
                           :sunray_logo,
                           :to_from_address,
                           :usps_barcode,
                           :ariela_signature,
                           :add_completed_date,
                           :add_todays_date
      end   
                           
                             
                            
      config.show.label = "Show Document"  
      config.show.columns = :state, 
                           :documentparent,  
                           :document_legal_name,                         
                           :document_type,
                           :default_amount
      config.show.columns.add_subgroup "Options" do |options_group|
        options_group.add :signer,
                           :delivery_date_on_notice,
                           :total_amount_of_job,
                           :balance_remaining,
                           :use_default_amount,
                           :soft_letter,
                           :sunray_logo,
                           :to_from_address,
                           :usps_barcode,
                           :ariela_signature,
                           :add_completed_date,
                           :add_todays_date
      end   
                           
                            
      
      list.columns.exclude :name,
                           :price,
                           :rules,
                           :content,
                           :soft_letter,
                           :sunray_logo,
                           :to_from_address,
                           :usps_barcode,
                           :ariela_signature,
                           :add_completed_date,
                           :add_todays_date,
                           :default_amount,
                           :signer,
                           :delivery_date_on_notice,
                           :total_amount_of_job,
                           :balance_remaining,
                           :use_default_amount, 
                           :created_at, 
                           :updated_at
            end 
 

                
end  

app/helpers/documents_helper.rb
module DocumentsHelper
  
 
end

app/views/documents/x-edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/x-index.html.haml
= link_to "Add a New Document", new_document_path
.row-fluid
  .span12.widget
    .widget-header
      %span.title List of Documents
    .widget-content.table-container
      %table#demo-dtable-02.table.table-striped
        %thead
          %tr
            %th State
            %th Document Name
            %th Document Legal Name
            %th Type of Document
            %th Actions
        %tbody
          - documents.each do |a|
            %tr
              %td= a.state
              %td= a.name
              %td= a.type
              %td= a.soft_letter
              
              %td
                = link_to "view", document_path(a)
                = link_to "edit", edit_document_path(a)
                = link_to 'Delete', document_path(a), method: :delete, data: { confirm: 'Are you sure?' }
       
= link_to "Back", :back

app/views/documents/x-new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/x-show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/documents/x_form.html.erb
<%
  scope ||= nil
  subsection_id ||= nil
  show_unauthorized_columns = active_scaffold_config.send(form_action).show_unauthorized_columns
%>
<ol class="form" <%= "id=#{subsection_id}" unless subsection_id.nil? %> <%= "style=\"display: none;\"".html_safe if columns.collapsed %>>
  <% columns.each :for => @record, :crud_type => (:read if show_unauthorized_columns) do |column| %>
  <% column_css_class = column.css_class unless column.css_class.nil? || column.css_class.is_a?(Proc) %>
  <% authorized = show_unauthorized_columns ? @record.authorized_for?(:crud_type => form_action, :column => column.name) : true %>
  <% renders_as = column_renders_as(column) %>
  <% if renders_as == :subsection -%>
    <% subsection_id = sub_section_id(:sub_section => column.label) %>
  <li class="sub-section <%= column_css_class %>">
    <h5><%= column.label %></h5>
    <%= render :partial => 'form', :locals => { :columns => column, :subsection_id => subsection_id, :form_action => form_action, :scope => scope } %>
    <%= link_to_visibility_toggle(subsection_id, {:default_visible => !column.collapsed}) -%>
  </li>
  <% elsif renders_as == :subform and !override_form_field?(column) and authorized -%>
  <li class="sub-form <%= active_scaffold_config_for(column.association.klass).subform.layout %>-sub-form <%= column_css_class %> <%=column.name%>-sub-form" id="<%= sub_form_id(:association => column.name) %>">
    <%=raw render :partial => form_partial_for_column(column, renders_as), :locals => { :column => column, :scope => scope } -%>
  </li>
  <% else -%>
  <li class="form-element <%= 'required' if column.required? %> <%= column_css_class %>">
    <%=raw render :partial => form_partial_for_column(column, renders_as), :locals => { :column => column, :only_value => !authorized, :scope => scope } -%>
  </li>
  <% end -%>
  <% end -%>
</ol>

app/views/documents/y-index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= link_to 'Show', document %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_document_path %>