config/routes.rb
Sunray::Application.routes.draw do


  devise_for :admins,
    :controllers => {
      :sessions => "admins/sessions",
      :registrations => 'admins/registrations',
      :confirmations => 'admins/confirmations',
      :passwords => "admins/passwords",
      :unlocks => "admins/unlocks",
      :accounts => "admins/accounts"
  }


  devise_for :users, :controllers => { 
    registrations: 'devise/registrations', 
    :sessions => "devise/sessions", 
    :passwords => 'devise/passwords', 
    :confirmations => 'devise/confirmations' 
  }

  authenticate :admin do
    namespace :admins do
      #mount Resque::Server.new, at: '/resque'
      resources :dashboards
      resources :accounts
    end  
  match "/admins" => 'admins/dashboards#index', as: :admins_root
  end
  
  resources :documentparents do as_routes end
  resources :documents do as_routes end
  resources :documentparts do as_routes end  
  root to: 'pages#index'
end

app/models/account.rb
class Account < ActiveRecord::Base 
  has_many :users
  has_many :addresses
  has_many :branches
  has_many :regions
  attr_accessible :name, :phone, :fax, :website, :logo, :description, :addresses_attributtes
  accepts_nested_attributes_for :addresses 

  def primary_address
    addresses.where(:address_type => 'primary').first
  end

end

# == Schema Information
#
# Table name: shipping_addresses
# create_table "accounts", :force => true do |t|
#    t.string   "name",              :default => "", :null => false
#    t.string   "logo"
#    t.text     "description"
#    t.string   "phone"
#    t.string   "fax"
#    t.string   "website"
#    t.string   "active"
#    t.datetime "created_at",                        :null => false
#    t.datetime "updated_at",                        :null => false
#    t.integer  "representative_id"
#    t.string   "how_did_you_hear"
#    t.string   "contract_file"
#    t.string   "specific_notes"
#    t.string   "priviledges"
#    t.integer  "billing_option"

#ROUTES

   # admins_accounts GET    /admins/accounts(.:format)            admins/accounts#index
   #                        POST   /admins/accounts(.:format)            admins/accounts#create
   #     new_admins_account GET    /admins/accounts/new(.:format)        admins/accounts#new
   #    edit_admins_account GET    /admins/accounts/:id/edit(.:format)   admins/accounts#edit
   #         admins_account GET    /admins/accounts/:id(.:format)        admins/accounts#show
   #                        PUT    /admins/accounts/:id(.:format)        admins/accounts#update
   #                        DELETE /admins/accounts/:id(.:format)        admins/accounts#destroy

app/controllers/admins/accounts_controller.rb
class Admins::AccountsController < ApplicationController
  before_filter :authenticate_admin!
  layout 'dashboard'	
  expose(:accounts) { Account.scoped{} }
  expose(:account)
  def create
    if account.save
      flash[:notice] = 'Account was successfully created.'
      redirect_to admins_accounts_path
    else
      render action: "new"
    end
  end

  def update
    if account.save
      flash[:notice] = 'Account was successfully updated.'
      redirect_to admins_accounts_path
    else
      render action: "new"
    end
  end

  def destroy
    account.destroy
    redirect_to admins_accounts_path
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/admins/accounts/_form.html.haml
.span12.widget
  .widget-header
    %span.title
      %i.icol-wand
      New Account Wizard
    .toolbar
  .widget-content.form-container
    = form_for [:admins, account], :defaults => { :input_html => { :class => "form-horizontal wizard-form wizard-form-horizontal"}} do |a|

      %fieldset.wizard-step
        %legend.wizard-label
          %i.icon-book
          Basic Information
        .control-group
          = a.text_field :name
        .control-group
          = a.text_field :phone 
          = a.text_field :fax
        .control-group
          = a.text_field :website
        .control-group
          = a.text_field :logo
        .control-group
          = a.text_field :description 

      %fieldset.wizard-step
        %legend.wizard-label
          %i.icon-book
          Addressess
        .control-group
        = a.fields_for :address do |add|
          .control-group
          = add.text_field :address
          .control-group
          = add.text_field :city
          .control-group
          = add.text_field :state
          .control-group
          = add.text_field :zip
          .control-group
          = add.text_field :phone
          .control-group
          = add.text_field :address_type
        .form-actions.wizard-actions
          = a.submit

app/views/admins/accounts/edit.html.haml
%h1 Edit Account
= render 'form'

app/views/admins/accounts/index.html.haml
= link_to "Add a New Account", new_admins_account_path
.row-fluid
  .span12.widget
    .widget-header
      %span.title Current Accounts
    .widget-content.table-container
      %table#demo-dtable-02.table.table-striped
        %thead
          %tr
            %th Name
            %th Phone
            %th Fax
            %th Email
            %th Active
            %th Actions
        %tbody
          - accounts.each do |a|
            %tr
              %td= a.name
              %td= a.phone
              %td= a.fax
              %td= a.email
              %td= a.active
              %td
                = link_to "view", admins_account_path(a)
                = link_to "edit", edit_admins_account_path(a)
                = link_to 'Delete', admins_account_path(a), method: :delete, data: { confirm: 'Are you sure?' }
        %tfoot
          %tr
            %th Name
            %th Phone
            %th Fax
            %th Email
            %th
            %th
= link_to "Back", :back

app/views/admins/accounts/new.html.haml
= render 'form'

app/views/admins/accounts/show.html.haml
This is the account show page
= account.name