config/routes.rb
Sunray::Application.routes.draw do


  devise_for :admins,
    :controllers => {
      :sessions => "admins/sessions",
      :registrations => 'admins/registrations',
      :confirmations => 'admins/confirmations',
      :passwords => "admins/passwords",
      :unlocks => "admins/unlocks",
      :accounts => "admins/accounts"
  }


  devise_for :users, :controllers => { 
    registrations: 'devise/registrations', 
    :sessions => "devise/sessions", 
    :passwords => 'devise/passwords', 
    :confirmations => 'devise/confirmations' 
  }

  authenticate :admin do
    namespace :admins do
      #mount Resque::Server.new, at: '/resque'
      resources :dashboards
      resources :accounts
    end  
  match "/admins" => 'admins/dashboards#index', as: :admins_root
  end
  
  resources :documentparents do as_routes end
  resources :documents do as_routes end
  resources :documentparts do as_routes end  
  root to: 'pages#index'
end

app/views/layouts/account.html.haml
!!!
%html
  %head
    %title Sunray Admin
    = stylesheet_link_tag    "account", :media => "all"
    = javascript_include_tag "account"
    = csrf_meta_tags
    %link{:href => "/assets/bootstrap.css", :rel => "stylesheet"}/
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        = render 'shared/user_nav'
        .container
          = image_tag("logosunray.png")
    .container
      %p.notice
        = notice
      %p.alert
        = alert
      = yield

app/views/layouts/admins.html.haml
!!!
/[if lt IE 7] <html class="lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="lt-ie9" lang="en">
/ [if gt IE 8]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0, user-scalable=no", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    / Bootstrap Stylesheet
    = stylesheet_link_tag    "admins", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "login"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    %title Sunray Construction Notices:: Sunray Admin 
  %body
   
    =yield
    

app/views/layouts/application.html.haml
%html
  %head
    %title Sunray Notice Application
    = stylesheet_link_tag   "application", :media => "all"
    = stylesheet_link_tag   "active_scaffold_overrides"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        = render 'shared/user_nav'
        .container
        = image_tag("logosunray.png")
    .container
   
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Sunray Notice Application</title>
      <%= stylesheet_link_tag  "dashboard", :media => "all" %>
      <%= csrf_meta_tags %>
    </head>
    <body>

    <div id="wrapper">
        <header id="header" class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <div class="brand-wrap pull-left">
                        <%= link_to admins_root_path do %>
                            <div class="brand-img">                    
                                <%= image_tag 'logosunray.png'%>
                            </div>
                        <% end %>
                    </div>
                    
                    <div id="header-right" class="clearfix">
                        <div id="nav-toggle" data-toggle="collapse" data-target="#navigation" class="collapsed">
                            <i class="icon-caret-down"></i>
                        </div>
                        <div id="header-search">
                            <span id="search-toggle" data-toggle="dropdown">
                                <i class="icon-search"></i>
                            </span>
                            <form class="navbar-search">
                                <input type="text" class="search-query" placeholder="Search">
                            </form>
                        </div>
                        <!-- <div id="dropdown-lists">
                            <a class="item" href="#">
                                <span class="item-icon"><i class="icon-exclamation-sign"></i></span>
                                <span class="item-label">Notifications</span>
                                <span class="item-count">4</span>
                            </a>
                            <a class="item" href="mail.html">
                                <span class="item-icon"><i class="icon-envelope"></i></span>
                                <span class="item-label">Messages</span>
                                <span class="item-count">16</span>
                            </a>
                        </div> -->
                        
                        <div id="header-functions" class="pull-right">
                            <div id="user-info" class="clearfix">
                                <span class="info">
                                    Welcome
                                    <span class="name"><!-- %= current_admin.fullname  % --></span>
                                </span>
                                <div class="avatar">
                                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                                        <img src="/assets/pp.jpg" alt="Avatar">
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="profile.html"><i class="icol-user"></i> My Profile</a></li>
                                        <li><a href="#"><i class="icol-layout"></i> My Invoices</a></li>                                        
                                        <li class="divider"></li>
                                        <li><%= link_to 'Logout', destroy_admin_session_path, :method => :delete %></li>
                                    </ul>
                                </div>
                            </div>
                            <div id="logout-ribbon">
                                <%= link_to destroy_admin_session_path, :method => :delete do %> <i class="icon-off"></i> <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <div id="content-wrap">
            <div id="content">
                <div id="content-outer">
                    <div id="content-inner">
                        <aside id="sidebar">
                            <nav id="navigation" class="collapse">
                                <ul>
                                    <li class="active">
                                        <span title="General">
                                            <i class="icon-home"></i>
                                            <span class="nav-title">General</span>
                                        </span>
                                        <ul class="inner-nav">
                                            <li class="active"><%= link_to admins_root_path do %><i class="icol-dashboard"></i> Dashboard <% end %></li>
 
                                            <li><%= link_to admins_accounts_path, :class => 'stat summary' do %><i class="icol-lifebuoy"></i> Manage Accounts<% end %></li>
                                            <li><a href="grids.html"><i class="icol-grid"></i> Search Request </a></li>
                                            <li><a href="calendar.html"><i class="icol-calendar-2"></i> My Reminders </a></li>
                                        </ul>
                                    </li>
                                    <!-- <li>
                                        <span title="Table">
                                            <i class="icon-table"></i>
                                            <span class="nav-title">Table</span>
                                        </span>
                                        <ul class="inner-nav">
                                            <li><a href="tables.html"><i class="icol-style"></i> Static Tables</a></li>
                                            <li><a href="responsive_tables.html"><i class="icol-hammer-screwdriver"></i> Responsive Tables</a></li>
                                            <li><a href="data_tables.html"><i class="icol-table"></i> Data Tables</a></li>
                                            <li><a href="detail_view.html"><i class="icol-eye"></i> Detail View Table</a></li>
                                        </ul>
                                    </li> -->
                                    <li>
                                        <span title="Statistic">
                                            <i class="icon-graph"></i>
                                            <span class="nav-title">Reports</span>
                                        </span>
                                        <ul class="inner-nav">
                                            <li><a href="statistic.html"><i class="icol-chart-curve"></i> Statistical Elements</a></li>
                                            <li><a href="charts_gallery.html"><i class="icol-chart-pie"></i> Charts Gallery</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <span title="Form">
                                            <i class="icon-list"></i>
                                            <span class="nav-title">Message Center</span>
                                        </span>
                                        <ul class="inner-nav">
                                            <li><a href="form_layouts.html"><i class="icol-layout-select"></i> Form Layouts</a></li>
                                            <li><a href="form_elements.html"><i class="icol-ui-text-field-password"></i> Form Elements</a></li>
                                            <li><a href="form_wizard.html"><i class="icol-wand"></i> Form Wizard</a></li>
                                            <li><a href="form_validation.html"><i class="icol-accept"></i> Form Validation</a></li>
                                            <li><a href="wysiwyg.html"><i class="icol-pencil"></i> WYSIWYG</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <span title="Elements">
                                            <i class="icon-cogs"></i>
                                            <span class="nav-title"><%= link_to("My Settings", edit_admin_registration_path) %></span>
                                        </span>
                                        <ul class="inner-nav">
                                            <li><a href="ui_bootstrap.html"><i class="icol-ui-tab-content"></i> Bootstrap Elements</a></li>
                                            <li><a href="ui_components.html"><i class="icol-pipette"></i> Other Elements</a></li>
                                            <li><a href="alerts.html"><i class="icol-error"></i> Alerts and Notifications</a></li>
                                            <li><a href="boxes.html"><i class="icol-cog"></i> Widget Boxes</a></li>
                                            <li><a href="buttons.html"><i class="icol-joystick"></i> Buttons</a></li>
                                            <li><a href="file_uploader.html"><i class="icol-computer"></i> File Uploader</a></li>
                                            <li><a href="file_manager.html"><i class="icol-databases"></i> File Manager</a>
                                        </ul>
                                    </li>
                                    <!-- <li>
                                        <span title="Extra">
                                            <i class="icon-gift"></i>
                                            <span class="nav-title">Extra</span>
                                        </span>
                                        <ul class="inner-nav">
                                            <li><a href="profile.html"><i class="icol-user"></i> Profile Page</a></li>
                                            <li><a href="mail.html"><i class="icol-email"></i> Mail Page</a></li>
                                            <li><a href="widgets.html"><i class="icol-ruby"></i> Custom Widgets</a></li>
                                            <li><a href="gallery.html"><i class="icol-images"></i> Image Gallery</a>
                                            <li><a href="contacts.html"><i class="icol-vcard"></i> Contact List</a></li>
                                            <li><a href="404.html"><i class="icol-error"></i> Error Page (404)</a></li>
                                        </ul>
                                    </li> -->
                                </ul>
                            </nav>
                        </aside>

                        <div id="sidebar-separator"></div>
                        
                        <section id="main" class="clearfix">
                            <div id="main-header" class="page-header">
                                <ul class="breadcrumb">
                                    <li>
                                        <i class="icon-home"></i>Sunray
                                        <span class="divider">&raquo;</span>
                                    </li>
                                    <li>
                                        <a href="#">Dashboard</a>
                                    </li>
                                </ul>
                             </div>
                                <!-- SETTING ALL ALERTS r-->
                                <!-- <div id="alert_content">
                                    <p class="notice"><%= notice %> </p>
                                    <p class="alert"><%= alert %></p>
                                </div> -->
                            
                            <div id="main-content">
            
                                <div class="row-fluid">
                                    <%= yield %> 
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    
    <footer id="footer">
        <div class="footer-left">Sunray Construction Notice - UConstruction v 1.0 Beta </div>
        <div class="footer-right"><p>Copyright 2012. All Rights Reserved.</p></div>
    </footer>
    
</div>
 
<%= javascript_include_tag "application" %>

            
        
    </body>
</html>